import 'package:flutter/material.dart';import 'package:oga_artisan/core/app_export.dart';import 'package:oga_artisan/widgets/custom_elevated_button.dart';class DashboardMenuPageDraweritem extends StatelessWidget {const DashboardMenuPageDraweritem({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return Drawer(child: Container(width: 267.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 50.v), decoration: AppDecoration.fillOnPrimaryContainer, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgX, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 8.h), onTap: () {onTapImgX(context);}), SizedBox(height: 48.v), Padding(padding: EdgeInsets.only(left: 13.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgHomePrimary, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 13.h, top: 3.v), child: Text("Dashboard", style: CustomTextStyles.titleMediumPrimary18_1))])), SizedBox(height: 37.v), _buildAllAssignedApplicant(context), SizedBox(height: 37.v), _buildMyJobs(context), SizedBox(height: 39.v), GestureDetector(onTap: () {onTapSearch(context);}, child: Padding(padding: EdgeInsets.only(left: 12.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSearchPrimarycontainer, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 14.h, top: 3.v), child: Text("Messages", style: CustomTextStyles.titleMediumPrimaryContainer))]))), SizedBox(height: 37.v), _buildChangePassword(context), SizedBox(height: 38.v), _buildViewProfile(context), SizedBox(height: 39.v), _buildUpdateProfile(context), SizedBox(height: 38.v), Padding(padding: EdgeInsets.only(left: 13.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLogOut, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 13.h, top: 3.v), child: Text("Logout", style: CustomTextStyles.titleMediumPrimaryContainer))])), SizedBox(height: 38.v)]))); } 
/// Section Widget
Widget _buildAllAssignedApplicant(BuildContext context) { return CustomElevatedButton(height: 25.v, text: "All Assigned Applicant", margin: EdgeInsets.only(left: 12.h), leftIcon: Container(margin: EdgeInsets.only(right: 14.h), child: CustomImageView(imagePath: ImageConstant.imgBriefcase, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.titleMediumPrimaryContainer, onPressed: () {onTapAllAssignedApplicant(context);}); } 
/// Section Widget
Widget _buildMyJobs(BuildContext context) { return CustomElevatedButton(height: 24.v, width: 110.h, text: "My Jobs", margin: EdgeInsets.only(left: 13.h), leftIcon: Container(margin: EdgeInsets.only(right: 13.h), child: CustomImageView(imagePath: ImageConstant.imgSend, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.titleMediumPrimaryContainer, onPressed: () {onTapMyJobs(context);}); } 
/// Section Widget
Widget _buildChangePassword(BuildContext context) { return CustomElevatedButton(height: 24.v, text: "Change Password", margin: EdgeInsets.only(left: 13.h, right: 37.h), leftIcon: Container(margin: EdgeInsets.only(right: 13.h), child: CustomImageView(imagePath: ImageConstant.imgLock, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.titleMediumPrimaryContainer, onPressed: () {onTapChangePassword(context);}); } 
/// Section Widget
Widget _buildViewProfile(BuildContext context) { return CustomElevatedButton(height: 24.v, width: 140.h, text: "View Profile", margin: EdgeInsets.only(left: 13.h), leftIcon: Container(margin: EdgeInsets.only(right: 13.h), child: CustomImageView(imagePath: ImageConstant.imgUser, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.titleMediumPrimaryContainer, onPressed: () {onTapViewProfile(context);}); } 
/// Section Widget
Widget _buildUpdateProfile(BuildContext context) { return CustomElevatedButton(height: 24.v, width: 160.h, text: "Update Profile", margin: EdgeInsets.only(left: 13.h), leftIcon: Container(margin: EdgeInsets.only(right: 13.h), child: CustomImageView(imagePath: ImageConstant.imgUserplus, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.titleMediumPrimaryContainer, onPressed: () {onTapUpdateProfile(context);}); } 
/// Navigates to the dashboardPageScreen when the action is triggered.
onTapImgX(BuildContext context) { Navigator.pushNamed(context, AppRoutes.dashboardPageScreen); } 
/// Navigates to the viewCandidatesPageTwoScreen when the action is triggered.
onTapAllAssignedApplicant(BuildContext context) { Navigator.pushNamed(context, AppRoutes.viewCandidatesPageTwoScreen); } 
/// Navigates to the myJobsPageScreen when the action is triggered.
onTapMyJobs(BuildContext context) { Navigator.pushNamed(context, AppRoutes.myJobsPageScreen); } 
/// Navigates to the messagePageScreen when the action is triggered.
onTapSearch(BuildContext context) { Navigator.pushNamed(context, AppRoutes.messagePageScreen); } 
/// Navigates to the changePasswordPageScreen when the action is triggered.
onTapChangePassword(BuildContext context) { Navigator.pushNamed(context, AppRoutes.changePasswordPageScreen); } 
/// Navigates to the profilePageScreen when the action is triggered.
onTapViewProfile(BuildContext context) { Navigator.pushNamed(context, AppRoutes.profilePageScreen); } 
/// Navigates to the updateProfilePageScreen when the action is triggered.
onTapUpdateProfile(BuildContext context) { Navigator.pushNamed(context, AppRoutes.updateProfilePageScreen); } 
 }
