import 'package:flutter/material.dart';import 'package:oga_artisan/core/app_export.dart';import 'package:oga_artisan/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:oga_artisan/widgets/app_bar/appbar_subtitle.dart';import 'package:oga_artisan/widgets/app_bar/appbar_subtitle_six.dart';import 'package:oga_artisan/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:oga_artisan/widgets/app_bar/custom_app_bar.dart';import 'package:oga_artisan/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class MessagePageChattingOneScreen extends StatelessWidget {MessagePageChattingOneScreen({Key? key}) : super(key: key);

TextEditingController messageController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [Spacer(), Align(alignment: Alignment.center, child: Container(width: 82.h, padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 1.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Text("September 17", style: theme.textTheme.labelMedium))), SizedBox(height: 26.v), SizedBox(height: 38.v, width: 109.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgRectangle25, height: 38.v, width: 109.h, alignment: Alignment.center), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 7.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("Am good", style: CustomTextStyles.bodySmallOnPrimaryContainer)), Padding(padding: EdgeInsets.only(left: 8.h, top: 6.v), child: Text("13:38", style: CustomTextStyles.bodySmallOnPrimaryContainer9))])))])), SizedBox(height: 8.v), SizedBox(height: 38.v, width: 134.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgRectangle25, height: 38.v, width: 134.h, alignment: Alignment.center), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 7.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 4.v), child: Text("Pls who is this", style: CustomTextStyles.bodySmallOnPrimaryContainer)), Padding(padding: EdgeInsets.only(left: 7.h, top: 8.v), child: Text("13:38", style: CustomTextStyles.bodySmallOnPrimaryContainer9))])))]))])), bottomNavigationBar: _buildMessage(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 79.v, leadingWidth: 49.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgGroup51, margin: EdgeInsets.only(left: 7.h, top: 2.v, bottom: 13.v), onTap: () {onTapIconButton(context);}), centerTitle: true, title: Column(children: [AppbarSubtitle(text: "Elizabeth"), SizedBox(height: 6.v), AppbarSubtitleSix(text: "Connecting...", margin: EdgeInsets.only(left: 11.h, right: 12.h))]), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgEllipse19, margin: EdgeInsets.only(left: 25.h, right: 25.h, bottom: 12.v))]); } 
/// Section Widget
Widget _buildMessage(BuildContext context) { return Container(margin: EdgeInsets.only(left: 12.h, right: 12.h, bottom: 36.v), decoration: AppDecoration.fillPrimaryContainer, child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgFrame26, height: 48.adaptSize, width: 48.adaptSize), Expanded(child: Padding(padding: EdgeInsets.only(left: 11.h, top: 9.v, bottom: 9.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomTextFormField(controller: messageController, hintText: "Message", hintStyle: CustomTextStyles.labelLarge13, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 8.v, 10.h, 7.v), child: CustomImageView(imagePath: ImageConstant.imgGroup, height: 14.adaptSize, width: 14.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 29.v), contentPadding: EdgeInsets.only(left: 16.h, top: 6.v, bottom: 6.v), borderDecoration: TextFormFieldStyleHelper.fillBlack, fillColor: appTheme.black900.withOpacity(0.64))), CustomImageView(imagePath: ImageConstant.imgVectorBlueGray400, height: 20.v, width: 15.h, margin: EdgeInsets.only(left: 23.h, top: 5.v, bottom: 4.v))])))])); } 
/// Navigates to the messagePageOneScreen when the action is triggered.
onTapIconButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.messagePageOneScreen); } 
 }
