import '../job_posts_page_2_one_screen/widgets/frametwo4_item_widget.dart';import 'package:flutter/material.dart';import 'package:oga_artisan/core/app_export.dart';import 'package:oga_artisan/widgets/app_bar/appbar_leading_image.dart';import 'package:oga_artisan/widgets/app_bar/appbar_trailing_image.dart';import 'package:oga_artisan/widgets/app_bar/custom_app_bar.dart';import 'package:oga_artisan/widgets/custom_elevated_button.dart';import 'package:oga_artisan/widgets/custom_icon_button.dart';import 'package:oga_artisan/widgets/custom_outlined_button.dart';import 'package:oga_artisan/widgets/custom_search_view.dart';import 'package:oga_artisan/presentation/job_posts_page_2_bottomsheet/job_posts_page_2_bottomsheet.dart';
// ignore_for_file: must_be_immutable
class JobPostsPage2OneScreen extends StatelessWidget {JobPostsPage2OneScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Good Morning ", style: theme.textTheme.titleLarge), TextSpan(text: "Lucy", style: CustomTextStyles.titleLargePrimary_1)]), textAlign: TextAlign.left))), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(left: 24.h, right: 25.h), child: CustomSearchView(controller: searchController, hintText: "Search")), SizedBox(height: 41.v), _buildFrameTwo(context), SizedBox(height: 39.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("Almost done! Add Job Criteria", style: CustomTextStyles.titleMediumSemiBold18))), SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("*Indicates required", style: CustomTextStyles.bodyMediumPrimaryContainer))), SizedBox(height: 29.v), _buildDescription(context), SizedBox(height: 22.v), Divider(indent: 24.h, endIndent: 25.h), SizedBox(height: 22.v), _buildApplicantCollection(context), SizedBox(height: 13.v), Divider(indent: 24.h, endIndent: 25.h), SizedBox(height: 17.v), _buildScreeningQuestions(context), SizedBox(height: 4.v), Divider(indent: 24.h, endIndent: 25.h), SizedBox(height: 95.v), Align(alignment: Alignment.centerLeft, child: Container(width: 350.h, margin: EdgeInsets.only(left: 24.h, right: 56.h), child: RichText(text: TextSpan(children: [TextSpan(text: "By continuing, you agree to ArtisanOga’s", style: CustomTextStyles.bodyMediumPrimaryContainer_1), TextSpan(text: " "), TextSpan(text: "Jobs Terms\nand Conditions", style: CustomTextStyles.titleSmallPrimaryMedium_2), TextSpan(text: " "), TextSpan(text: "including our", style: CustomTextStyles.bodyMediumPrimaryContainer_1), TextSpan(text: " "), TextSpan(text: "policies prohibiting\ndiscriminatory job posts.", style: CustomTextStyles.titleSmallPrimaryMedium_2)]), textAlign: TextAlign.left))), SizedBox(height: 14.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomOutlinedButton(height: 41.v, width: 97.h, text: "Back", buttonStyle: CustomButtonStyles.outlinePrimaryContainer, buttonTextStyle: CustomTextStyles.titleMediumSemiBold18, onPressed: () {onTapBack(context);}), CustomElevatedButton(height: 41.v, width: 110.h, text: "Post Job", margin: EdgeInsets.only(left: 18.h), buttonStyle: CustomButtonStyles.fillPrimaryContainerTL20, buttonTextStyle: CustomTextStyles.titleMediumOnPrimaryContainerSemiBold18, onPressed: () {onTapPostJob(context);})]))), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 54.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgJamMenuIcon, margin: EdgeInsets.only(left: 16.h, top: 9.v, bottom: 9.v)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgGroup119, margin: EdgeInsets.symmetric(horizontal: 22.h, vertical: 16.v))]); } 
/// Section Widget
Widget _buildFrameTwo(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Wrap(runSpacing: 5.v, spacing: 5.h, children: List<Widget>.generate(1, (index) => Frametwo4ItemWidget()))); } 
/// Section Widget
Widget _buildDescription(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h, right: 40.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(children: [Text("Description*", style: CustomTextStyles.titleMedium18), SizedBox(height: 8.v), Text("Add description", style: CustomTextStyles.titleSmallPrimaryMedium_1)]), CustomImageView(imagePath: ImageConstant.imgSimpleLineIconsPencil, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 16.v, bottom: 6.v))]))); } 
/// Section Widget
Widget _buildApplicantCollection(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 24.h, right: 34.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Applicant collection*", style: CustomTextStyles.titleMedium18), SizedBox(height: 6.v), SizedBox(width: 215.h, child: Text("Add email or SMS to get notified\nwhen receiving applicants", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPrimaryContainer))]), Padding(padding: EdgeInsets.only(top: 10.v, bottom: 19.v), child: CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.outlinePrimary, onTap: () {onTapBtnPlus(context);}, child: CustomImageView(imagePath: ImageConstant.imgPlus)))])); } 
/// Section Widget
Widget _buildScreeningQuestions(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 24.h, right: 34.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Screening questions*", style: CustomTextStyles.titleMedium18), SizedBox(height: 6.v), SizedBox(width: 228.h, child: Text("Add questions to identify qualified\napplicants.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPrimaryContainer))]), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 23.v), child: CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.outlinePrimary, child: CustomImageView(imagePath: ImageConstant.imgPlus)))])); } 

/// Shows a modal bottom sheet with [JobPostsPage2Bottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapBtnPlus(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>JobPostsPage2Bottomsheet(),isScrollControlled: true); } 
/// Navigates to the jobPostsPage1Screen when the action is triggered.
onTapBack(BuildContext context) { Navigator.pushNamed(context, AppRoutes.jobPostsPage1Screen); } 

/// Shows a modal bottom sheet with [JobPostsPage2Bottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapPostJob(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>JobPostsPage2Bottomsheet(),isScrollControlled: true); } 
 }
