import 'package:flutter/material.dart';import 'package:oga_artisan/core/app_export.dart';import 'package:oga_artisan/widgets/app_bar/appbar_leading_iconbutton_two.dart';import 'package:oga_artisan/widgets/app_bar/appbar_subtitle_two.dart';import 'package:oga_artisan/widgets/app_bar/custom_app_bar.dart';import 'package:oga_artisan/widgets/custom_elevated_button.dart';class SettingsPageOneScreen extends StatelessWidget {const SettingsPageOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 25.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildRacoon(context), SizedBox(height: 24.v), Divider(indent: 1.h), SizedBox(height: 27.v), CustomElevatedButton(height: 22.v, width: 174.h, text: "Change Password", margin: EdgeInsets.only(left: 9.h), leftIcon: Container(margin: EdgeInsets.only(right: 19.h), child: CustomImageView(imagePath: ImageConstant.imgVectorPrimarycontainer, height: 21.v, width: 16.h)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleMedium!, onPressed: () {onTapChangePassword(context);}), SizedBox(height: 33.v), CustomElevatedButton(height: 20.v, width: 145.h, text: "Update Profile", margin: EdgeInsets.only(left: 9.h), leftIcon: Container(margin: EdgeInsets.only(right: 15.h), child: CustomImageView(imagePath: ImageConstant.imgTrendingup, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleMedium!, onPressed: () {onTapUpdateProfile(context);}), SizedBox(height: 34.v), Padding(padding: EdgeInsets.only(left: 8.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLogOutPrimarycontainer, height: 22.adaptSize, width: 22.adaptSize), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("Log out", style: theme.textTheme.titleMedium))])), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 117.v, leadingWidth: 58.h, leading: AppbarLeadingIconbuttonTwo(imagePath: ImageConstant.imgArrowLeftOnprimarycontainer, margin: EdgeInsets.only(left: 10.h, top: 59.v, bottom: 10.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleTwo(text: "Settings", margin: EdgeInsets.only(left: 4.h, top: 72.v, bottom: 17.v)), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildRacoon(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 152.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse7057x57, height: 57.adaptSize, width: 57.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(top: 4.v, bottom: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("Racoon", style: CustomTextStyles.titleLargePrimary)), SizedBox(height: 1.v), Text("FreeLancer", style: CustomTextStyles.titleSmallBluegray400Medium)]))])), CustomImageView(imagePath: ImageConstant.imgVectorPrimary, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(top: 24.v, bottom: 15.v))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the changePasswordPageOneScreen when the action is triggered.
onTapChangePassword(BuildContext context) { Navigator.pushNamed(context, AppRoutes.changePasswordPageOneScreen); } 
/// Navigates to the updateProfilePageOneScreen when the action is triggered.
onTapUpdateProfile(BuildContext context) { Navigator.pushNamed(context, AppRoutes.updateProfilePageOneScreen); } 
 }
