import 'package:flutter/material.dart';import 'package:oga_artisan/core/app_export.dart';import 'package:oga_artisan/widgets/app_bar/appbar_leading_image.dart';import 'package:oga_artisan/widgets/app_bar/appbar_subtitle_two.dart';import 'package:oga_artisan/widgets/app_bar/custom_app_bar.dart';class EmployerProfilePage1Screen extends StatelessWidget {const EmployerProfilePage1Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildArrowLeft(context), Container(padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 37.v), child: Column(children: [_buildSettings(context), SizedBox(height: 71.v), Text("Back to Home", style: CustomTextStyles.titleMediumBold), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return SizedBox(height: 426.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: SizedBox(height: 204.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgEllipse371, height: 204.v, width: 430.h, alignment: Alignment.center), CustomAppBar(height: 95.v, leadingWidth: 45.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 21.h, top: 2.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "Candidate’s Profile"))]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 25.h), padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 18.v), decoration: AppDecoration.outlineBlack9004.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgEllipse401, height: 75.adaptSize, width: 75.adaptSize, radius: BorderRadius.circular(37.h)), SizedBox(height: 16.v), Text("George Steve", style: CustomTextStyles.titleLargePrimary23), SizedBox(height: 2.v), Text("Affiliate Marketer", style: CustomTextStyles.bodyLargeGray500), SizedBox(height: 19.v), Divider(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 67.h, right: 62.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 6.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgIcBaselinePhone, height: 25.adaptSize, width: 25.adaptSize), SizedBox(height: 10.v), Text("Audio", style: CustomTextStyles.titleMediumPrimary)])), Spacer(), GestureDetector(onTap: () {onTapFluentVideoFilled(context);}, child: Column(children: [CustomImageView(imagePath: ImageConstant.imgFluentVideo20Filled, height: 35.adaptSize, width: 35.adaptSize), SizedBox(height: 6.v), Text("Video", style: CustomTextStyles.titleMediumPrimary)])), Padding(padding: EdgeInsets.only(left: 30.h, top: 6.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgSearchPrimary, height: 24.adaptSize, width: 24.adaptSize), SizedBox(height: 11.v), Text("Search", style: CustomTextStyles.titleMediumPrimary)]))])), SizedBox(height: 12.v)])))])); } 
/// Section Widget
Widget _buildSettings(BuildContext context) { return Container(width: 380.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 22.v), decoration: AppDecoration.outlineBlack9004.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 19.adaptSize, width: 19.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("+122 234 764 345 67", style: CustomTextStyles.titleSmallPrimary15))]), SizedBox(height: 23.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgMail, height: 22.adaptSize, width: 22.adaptSize), Padding(padding: EdgeInsets.only(left: 13.h, top: 2.v), child: Text("georgejfdg@gmail.com", style: CustomTextStyles.titleSmallPrimary15))])])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the callPageChattingTwoScreen when the action is triggered.
onTapFluentVideoFilled(BuildContext context) { Navigator.pushNamed(context, AppRoutes.callPageChattingTwoScreen); } 
 }
