import 'package:flutter/material.dart';import 'package:oga_artisan/core/app_export.dart';import 'package:oga_artisan/widgets/custom_elevated_button.dart';import 'package:oga_artisan/widgets/custom_outlined_button.dart';class CandidatesProfileAcceptPageScreen extends StatelessWidget {const CandidatesProfileAcceptPageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildCandidateSProfile(context), SizedBox(height: 37.v), _buildEighteen(context), SizedBox(height: 35.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(height: 46.v, width: 160.h, text: "Message", buttonStyle: CustomButtonStyles.fillPrimaryTL23, buttonTextStyle: CustomTextStyles.titleLargeOnPrimaryContainer22, onPressed: () {onTapMessage(context);}), CustomOutlinedButton(height: 46.v, width: 115.h, text: "Call", margin: EdgeInsets.only(left: 25.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL23, buttonTextStyle: CustomTextStyles.titleLargePrimary, onPressed: () {onTapCall(context);})]), SizedBox(height: 51.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 148.h), child: Text("Back to Home", style: CustomTextStyles.titleMediumPrimarySemiBold))), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildCandidateSProfile(BuildContext context) { return SizedBox(height: 426.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: SizedBox(height: 204.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgEllipse37, height: 204.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 68.v), child: Text("Candidate’s Profile", style: CustomTextStyles.titleLargeOnPrimaryContainer22)))]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 25.h), padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 23.v), decoration: AppDecoration.outlineBlack9004.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgEllipse5, height: 75.adaptSize, width: 75.adaptSize, radius: BorderRadius.circular(37.h)), SizedBox(height: 8.v), Text("Chloé Scarlett", style: CustomTextStyles.titleLargePrimary23), SizedBox(height: 5.v), Text("Freelancer", style: CustomTextStyles.bodyLargeGray500), SizedBox(height: 19.v), Divider(), SizedBox(height: 14.v), Container(width: 322.h, margin: EdgeInsets.symmetric(horizontal: 8.h), child: Text("Chloé Scarlett is a freelance expertise with 3 years of experience helping her target clients achieve their goals.", maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray500)), SizedBox(height: 10.v)])))])); } 
/// Section Widget
Widget _buildEighteen(BuildContext context) { return Container(width: 380.h, margin: EdgeInsets.symmetric(horizontal: 25.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 22.v), decoration: AppDecoration.outlineBlack9004.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 19.adaptSize, width: 19.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("+323 546 967 231 69", style: CustomTextStyles.titleSmallPrimary15))]), SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(right: 80.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMail, height: 22.adaptSize, width: 22.adaptSize), Padding(padding: EdgeInsets.only(left: 11.h, top: 2.v), child: Text("stylishracoon3637@gmail.com", style: CustomTextStyles.titleSmallPrimary15))]))])); } 
/// Navigates to the messagePageChattingWithApplicantScreen when the action is triggered.
onTapMessage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.messagePageChattingWithApplicantScreen); } 
/// Navigates to the callPageChattingScreen when the action is triggered.
onTapCall(BuildContext context) { Navigator.pushNamed(context, AppRoutes.callPageChattingScreen); } 
 }
