import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:oga_artisan/core/app_export.dart';import 'package:oga_artisan/widgets/app_bar/appbar_leading_image.dart';import 'package:oga_artisan/widgets/app_bar/appbar_trailing_image.dart';import 'package:oga_artisan/widgets/app_bar/custom_app_bar.dart';import 'package:oga_artisan/widgets/custom_elevated_button.dart';import 'package:oga_artisan/widgets/custom_outlined_button.dart';import 'package:oga_artisan/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class ManageJobsPageScreen extends StatelessWidget {ManageJobsPageScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 25.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 25.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Good Morning ", style: theme.textTheme.titleLarge), TextSpan(text: "Lucy", style: CustomTextStyles.titleLargePrimary_1)]), textAlign: TextAlign.left)), SizedBox(height: 24.v), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomSearchView(controller: searchController, hintText: "Search", alignment: Alignment.center))), SizedBox(height: 42.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("Manage job posts", style: CustomTextStyles.titleMediumSemiBold18)), SizedBox(height: 29.v), _buildMer(context), SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgOiPeople, height: 21.adaptSize, width: 21.adaptSize), Padding(padding: EdgeInsets.only(left: 9.h, top: 3.v), child: Text("0 applicants", style: CustomTextStyles.titleSmallMedium_1)), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(left: 10.h, top: 9.v, bottom: 8.v), decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), Padding(padding: EdgeInsets.only(left: 9.h, top: 2.v), child: Text("0 views", style: CustomTextStyles.titleSmallPrimaryMedium_1))])), SizedBox(height: 22.v), _buildViewApplicants(context), SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("Job Description", style: theme.textTheme.titleMedium)), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("You must be skilled and intelligent minded person", style: CustomTextStyles.bodyMediumPrimaryContainer)), SizedBox(height: 18.v), Align(alignment: Alignment.center, child: Divider(indent: 24.h, endIndent: 25.h)), SizedBox(height: 302.v), CustomElevatedButton(height: 70.v, text: "See more", buttonStyle: CustomButtonStyles.fillPrimary1, buttonTextStyle: CustomTextStyles.titleLargeOnPrimaryContainer22, onPressed: () {onTapSeeMore(context);}), SizedBox(height: 26.v), CustomImageView(imagePath: ImageConstant.imgJobDescription, height: 15.v, width: 118.h, margin: EdgeInsets.only(left: 25.h)), SizedBox(height: 13.v), CustomImageView(imagePath: ImageConstant.imgYouMustBeASkilled, height: 13.v, width: 338.h, margin: EdgeInsets.only(left: 25.h))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 54.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgJamMenuIcon, margin: EdgeInsets.only(left: 16.h, top: 9.v, bottom: 9.v)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgGroup119, margin: EdgeInsets.symmetric(horizontal: 22.h, vertical: 16.v))]); } 
/// Section Widget
Widget _buildMer(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 57.v, width: 56.h, margin: EdgeInsets.only(bottom: 7.v), padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 8.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup173), fit: BoxFit.cover)), child: CustomImageView(imagePath: ImageConstant.img9689687150Mer, height: 39.v, width: 42.h, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 16.h, top: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Assistant", style: CustomTextStyles.titleMediumPrimary18_1), Text("Ibadan (On-Site)", style: CustomTextStyles.titleSmallGray500), SizedBox(height: 1.v), SizedBox(width: 169.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Active", style: CustomTextStyles.titleSmallLightgreen900), CustomImageView(imagePath: ImageConstant.imgMingcuteQuestionFill, height: 18.adaptSize, width: 18.adaptSize), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.symmetric(vertical: 7.v), decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), Text("Posted today", style: CustomTextStyles.titleSmallPrimaryMedium_1)]))])), Spacer(), CustomImageView(imagePath: ImageConstant.imgHumbleiconsPencil, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 17.v, bottom: 23.v))]))); } 
/// Section Widget
Widget _buildViewApplicants(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 26.h, right: 45.h), child: Row(children: [CustomOutlinedButton(height: 34.v, width: 153.h, text: "View Applicants", buttonTextStyle: CustomTextStyles.titleMediumPrimarySemiBold_1, onPressed: () {onTapViewApplicants(context);}), CustomOutlinedButton(height: 34.v, width: 200.h, text: "Professional Features", margin: EdgeInsets.only(left: 6.h), buttonTextStyle: CustomTextStyles.titleMediumPrimarySemiBold_1, onPressed: () {onTapProfessionalFeatures(context);})])); } 
/// Navigates to the viewCandidatesPageScreen when the action is triggered.
onTapViewApplicants(BuildContext context) { Navigator.pushNamed(context, AppRoutes.viewCandidatesPageScreen); } 
/// Navigates to the professionalFeaturesPageScreen when the action is triggered.
onTapProfessionalFeatures(BuildContext context) { Navigator.pushNamed(context, AppRoutes.professionalFeaturesPageScreen); } 
/// Navigates to the myJobsPageScreen when the action is triggered.
onTapSeeMore(BuildContext context) { Navigator.pushNamed(context, AppRoutes.myJobsPageScreen); } 
 }
